[log]
level = "off"

[network]
use_udp = true
zero_copy = true

[[endpoints]]
listen = "0.0.0.0:45416"
remote = "127.0.0.1:2898"
listen_transport = "ws;host=xinhuanet.com;path=/snwazfcts;tls;servername=news.cn"
remote_transport = ""
